name: black-command
on:
  repository_dispatch:
    types: [black-command]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull request branch
      - uses: actions/checkout@v2.1.0
        with:
          token: ${{ secrets.PR_MAINTAIN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      # Setup Python environment
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Set cache id
      - name: Cache weekly timestamp
        id: pip-cache
        run: echo "::set-output name=datew::$(date '+%Y-%V')"
        shell: bash

      # Set cache (linux only)
      - name: Cache for pip
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ steps.pip-cache.outputs.datew }}

      - name: Install isort black autopep8
        run: pip install isort black autopep8 torch numpy

      # Execute autopep8 and black
      - name: Autopep8 isort Black
        id: black
        run: |
          autopep8 --version
          isort --version
          black --version

          autopep8 --recursive --in-place --aggressive --aggressive .
          isort .
          black .

          ./runtests.sh --clangformat

          changes=
          if [ -n "$(git status --porcelain)" ]; then
            changes="true"
          fi
          echo ::set-output name=format::$changes
        shell: bash

      # Commit the change to the PR branch
      - name: Commit to the PR branch
        if: steps.black.outputs.format == 'true'
        run: |
          git config --global user.name 'monai-bot'
          git config --global user.email 'monai.miccai2019@gmail.com'
          git commit -sam "[MONAI] python code formatting"
          git push

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PR_MAINTAIN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
